/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agenda.control;

import org.junit.jupiter.api.Test;

import agenda.control.Agenda;

import static org.junit.jupiter.api.Assertions.*;

class AgendaTest {

}
